trigger:
 - none

pr:
  branches:
    include:
    - 'master' 

pool:
  vmImage: ubuntu-latest
variables:
- group: Semgrep app token group

steps: 

- script: |
    python -m pip install --upgrade pip
    pip install semgrep
    printenv
    semgrep ci
  env: 
    SEMGREP_PR_ID: ${SYSTEM_PULLREQUEST_PULLREQUESTNUMBER}
    SEMGREP_BASELINE_REF: 'origin/master'