trigger:
 - master

pool:
  vmImage: ubuntu-latest
variables:
- group: Semgrep app token group

# resources:
#   repositories:
#   - repository: Hemomancers-1 # The name used to reference this repository in the checkout step
#     type: github
#     name: holdenmcg/Hemomancers-1
#     ref: master

steps: 

- script: |
    python -m pip install --upgrade pip
    pip install semgrep
    semgrep ci
  env: 
    SEMGREP_PR_ID: $(System.PullRequest.PullRequestNumber)
    SEMGREP_BASELINE_REF: 'hm/azure-pr-test-2'