schedules:
- cron: "0 0 * * *"
  displayName: Every day at midnight
  branches:
    include:
    - master
trigger:
- none
pr: none
pool:
  vmImage: ubuntu-latest
variables:
- group: Semgrep app token group
steps: 
- script: |
    python -m pip install --upgrade pip
    pip install semgrep
    semgrep ci
  env: 
    SEMGREP_PR_ID: $(System.PullRequest.PullRequestNumber)
  displayName: 'Run a full Semgrep scan of the default branch every day at Midnight'.