# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pr:
- master

pool:
  vmImage: ubuntu-latest
variables:
- group: Semgrep app token group
steps:
- script: |
    export $SEMGREP_PR_ID=System.System.PullRequest.PullRequestNumber
    printenv
  displayName: 'Set environment variables'

- script: |
    python -m pip install --upgrade pip
    pip install semgrep
    semgrep ci 
    printenv
  env: 
    SEMGREP_PR_ID: $(System.PullRequest.PullRequestId)
    TEST_ENV: "hahahahah testing hahahahaha"

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
